# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
   targetType: 'inline'
   script: |
    i=0
    end=30
        while [ $i -lt $end ]
        do
            i=$(( $i + 1 ))
            curl --location --request POST 'https://app.armorcode.com/client/buildvalidation' --header 'Content-Type: application/json' --header 'Authorization: Bearer $(ARMORCODE_TOKEN)'  -d '{ "env": "Production", "product": "2859", "subProduct": "7787", "buildTool":"AZURE_PIPELINE", "buildNumber": "$(Build.BuildId)","current":"'$i'" , "end":"'$end'"}' > result.json
            status=$(jq -r '.status' result.json)
            if [ $status = "HOLD" ]
            then
                echo "Armorcode SLA failed."
                sleep 10
                echo "Sleeping 10 seconds before trying again. You can temporarily release the build from Armorcode console"
            elif [ $status = "FAILED" ]
            then
                echo "Exiting with error code 1"
                exit 1
            else
                break
            fi           
        done